// <auto-generated />
using System;
using ConsoleApp_SarahahTelegrambot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp_SarahahTelegrambot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241030165530_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp_SarahahTelegrambot.MessageInfoModel", b =>
                {
                    b.Property<int>("SenderMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ReceiverChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReceiverMessageId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SenderChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SenderMessageId");

                    b.HasIndex("SenderChatId");

                    b.ToTable("tblMessages");
                });

            modelBuilder.Entity("ConsoleApp_SarahahTelegrambot.UserModel", b =>
                {
                    b.Property<long>("LongSenderChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LongLastReceiverChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("StringSenderChatId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("LongSenderChatId");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("ConsoleApp_SarahahTelegrambot.MessageInfoModel", b =>
                {
                    b.HasOne("ConsoleApp_SarahahTelegrambot.UserModel", "User")
                        .WithMany("MessagesInfo")
                        .HasForeignKey("SenderChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConsoleApp_SarahahTelegrambot.UserModel", b =>
                {
                    b.Navigation("MessagesInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
